### ISSUE TITLE
help with no pdf creation

### ISSUE THREAD

**Issue by pacija** [iusvar/grav-plugin-snappygrav#1]
Hi,
I'm completely new to grav, and I'm having trouble get your plugin to work.

I installed plugin via gpm, dependencies (amd64 one) via composer, copied user/plugins/snappygrav/snappygrav.yaml into user/config/plugins/snappygrav.yaml and set correct path to wk_path. I have also set Absolute URLs to true.

I'm using Learn2 theme (added to clean install, no skeleton), and I've replaced code in github_link.html.twig with your code. PDF icon appears, but clicking it complains about non-existing templates dir - user/plugins/snappygrav/templates. I've created the dir, but clicking PDF icon just brings me back to homepage.

Any idea where to start troubleshooting? Thank you in advance.

**Comment by iusvar** [comment]
Hi,
I too am new to GRAV, about four months ...
I built the plugin SnappyGrav for use with Blog Site skeleton & Antimatter theme and I realize now not to have written it in the README, I apologize for that ...
But I really like the idea that you had to use it with RTFM Site skeleton & Learn2 theme.
I recreated on my PC that you are getting the error and I hope to resolve it as soon as possible.
Meanwhile, thanks to you.

**Comment by iusvar** [comment]
Hi,
I made the appropriate changes to correct the error returned by you.
You can find the new version, to download, to the following address: https://github.com/iusvar/grav-plugin-snappygrav/archive/master.zip
Now it should work, I close this issue.
Thanks for your feedback.
