### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by lauroguedes** [iusvar/grav-plugin-snappygrav#10]
When I try access the url page, happen this
![error-snappdfplugin](https://cloud.githubusercontent.com/assets/3677780/23659679/adced31c-0325-11e7-9b61-40405ec38508.PNG)

**Comment by iusvar** [comment]
Published version 1.2.0 that fixes the problem

**Comment by rbukovansky** [comment]
@lauroguedes I can confirm, that version 1.2.0 fixes the problem.

**Comment by lauroguedes** [comment]
@rbukovansky yet is with the problem, you can look in the project - https://goo.gl/1quUDL
in param 'slug_blog' of the config it is 'blog'. This is have some influence?

**Comment by rbukovansky** [comment]
@lauroguedes That page needs me to log in. I don't have any credentials to that site. Could you provide some?

But as far as my not-developer eye can see, that config is only usable when using `Antimatter` theme, but I might be wrong.

@iusvar Will you chime in? Thanks.

**Comment by iusvar** [comment]
@rbukovansky, I was doing that you have preceded me...

@lauroguedes, in the linked project where I can find the button to create the PDF?

The plugin is designed for Antimatter and Learn2: so the slug_blog parameter was added because someone might have a blog in a folder other than 'blog'.

**Comment by iusvar** [comment]
@lauroguedes now I'm watching...

**Comment by lauroguedes** [comment]
@rbukovansky I released the access, I developed the project on the Helium template for Grantry5

**Comment by lauroguedes** [comment]
@iusvar I'm trying to develop a skeleton template to write based on this template I made. So I think it's cool if this plugin works on this topic. If you want I can release the code for you to contribute with this project making your plugin work on it.

**Comment by iusvar** [comment]
@lauroguedes I was going to ask you if it was a theme similar to [grav-theme-knowledge-base] (https://github.com/Perlkonig/grav-theme-knowledge-base) of @Perlkonig

**Comment by lauroguedes** [comment]
@iusvar yes, but I want to do a bigger project with more features and responsive

**Comment by iusvar** [comment]
@lauroguedes okay, in the meantime I can make some attempt with that theme ... I not engage too much because I do not have enough time!

**Comment by lauroguedes** [comment]
no problem, as soon as I published it, I invite you

**Comment by iusvar** [comment]
@lauroguedes Hi, I am currently performing the latest checks before I create the next release that also contains the code for the original Knowledge Base theme by Perlkonig ...

**Comment by lauroguedes** [comment]
ok very good. I am working the my project of knowledge base theme too. Comon son I am going to rocket it.
