### ISSUE TITLE
Saving PDF file in Safari

### ISSUE THREAD

**Issue by rbukovansky** [iusvar/grav-plugin-snappygrav#14]
Hi, I'm not sure if it's snappygrav's issue or Safari's issue on Mac, but when I try to download PDF file in Safari it saves that as `.html` file, instead of `.pdf` file. The content seems like PDF file.
Any idea what could be wrong?
If I do the same in Chrome, Firefox, IE, it's all good.
Thanks.

**Comment by iusvar** [comment]
Hi, unfortunately I do not have a Mac, but this [thread on Apple site](https://discussions.apple.com/thread/5470838?tstart=0) could be the solution.
Good luck.

**Comment by rbukovansky** [comment]
Well, that thread is no go, as I don't have Adobe Reader installed and Safari is 10.x version.

Anyway, thank you!
