### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by christianhals** [iusvar/grav-plugin-snappygrav#16]
Is it possible to modify SnappyGrav to show breadcrumbs?

**Comment by iusvar** [comment]
I will add this option in the next release. Thank you for your suggestion.

**Comment by iusvar** [comment]
Released version 1.4.0 with breadcrumbs

**Comment by christianhals** [comment]
Thanks a lot for adding this feature. Looking forward to testing it on our installation.

**Comment by iusvar** [comment]
I am having problems installing my `snappygrav` with `Admin`.
A command line (`bin/gpm install snappygrav`) is no problem even if some warning appears.

I know the reason for the error / warning.

I'm preparing a issue for `grav-plugin-admin`

**Comment by christianhals** [comment]
Hi,

I noticed you had respond to the break error in another thread. I replaced with exit, but I cannot get around the invalid_response_error with this new version. As far as I can tell I have updated all the settings (which was working on your earlier version) and I can run the binary with  `vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64` from the root of my grav installation

I have also checked that the absolute path is set in **system.yaml** and this is my console log:

_Environment Name: *
info Knp\Snappy\Pdf OK
info wkhtmltopdf OK
info Cache: [true] Setting: [auto] Driver: [apcu]
info Page cache hit._

**Comment by iusvar** [comment]
Hi,

from version v1.3.1-rc.1 the `knp-snappy` and `wkhtmltopdf` libraries are located in the vendor folder of the plugin, then `your_site/user/plugins/snappygrav/vendor/*`

I just improved the README

**Comment by christianhals** [comment]
Thanks a lot iusvar. I installed wkhtmltopdf-amd64 package with composer from the plugin directory in stead of the webroot and that did the trick:-)
