### ISSUE TITLE
export of Branch

### ISSUE THREAD

**Issue by drymonsoon** [iusvar/grav-plugin-snappygrav#17]
Hello, I've been using snappygrav for a while and I'm not a php developer.
This is a proposal for an enhancement.
Right now it is possible to export or the whole site or a single page. I think it will be usefull to add an option to add the export of a branch/folder.

**Comment by iusvar** [comment]
Hi, I'm reviewing the whole procedure for which I will consider your suggestion. Thank you.

**Comment by drymonsoon** [comment]
Thank you very much! If I could help in any way just let me know

**Comment by drymonsoon** [comment]
Hello, sorry for bothering you, if you could point me in the direction of the modification I maybe write it and test it and then open a PR for the feature. I looked at the code and I can't find where to start adding the code.

**Comment by npanau** [comment]
Hi, I suggest you to have a look at SnappyGravPlugin::onCollectionProcessed which parses all site's pages.

**Comment by iusvar** [comment]
@drymonsoon, @npanau Hi, before I create the next release I am performing the latest checks on the three themes adopted. I have almost completely revised the code for which it would be approximate to provide any information ...
