### ISSUE TITLE
rtfm/learn2 error

### ISSUE THREAD

**Issue by MikeHewitt** [iusvar/grav-plugin-snappygrav#18]
Getting the following error with the rtfm/learn2 skeleton

'break' not in the 'loop' or 'switch' context in user/plugins/snappygrav/snappygrav.php on line 215

**Comment by iusvar** [comment]
Ooops! I forgot to replace `break` with `exit`

However when the program finds true this assumption means that the wkhtmltopdf library folder was not found

Thanks for the tip.
