### ISSUE TITLE
system wide wk_path settings?

### ISSUE THREAD

**Issue by npanau** [iusvar/grav-plugin-snappygrav#19]
Hi,

I have a problem with the new release ; the plugin can't find the path to wkhtmltopdf (wk_path) because you're looking for it in the vendors dir, or in the plugin dir.
I have wkhtmltopdf installed on the server, system wide (/usr/local/bin/wkhtmltopdf), but if I set this value for the wk_path, the lib is not found.
Plus I'm developping on OSX, and wkhtmltopdf installed via vendors do not seems to work.

Is it possible to use wkhtmltopdf while installed system wide?

Thanks in advance

**Comment by iusvar** [comment]
Okay, I'll consider it for next version 1.5.0
Bye

**Comment by npanau** [comment]
Marvelous!
Let me know if u want a PR on this.

**Comment by iusvar** [comment]
Thank you, not now, I'm about to upgrade even github with other changes...
