### ISSUE TITLE
grav.CRITICAL: 'break' not in the 'loop' or 'switch' context

### ISSUE THREAD

**Issue by jorgemfm** [iusvar/grav-plugin-snappygrav#20]
Hi, 

After upgrade from v1.2.4 to v1.3.1 I get this error:

> grav.CRITICAL: 'break' not in the 'loop' or 'switch' context - Trace: #0 /var/www/grav/vendor/filp/whoops/src/Whoops/Run.php(382): Whoops\Run->handleError(64, ''break' not in ...', '/var/www/grav...', 273) #1 /var/www/grav/system/src/Grav/Common/Errors/SystemFacade.php(36): Whoops\Run->handleShutdown() #2 [internal function]: Grav\Common\Errors\SystemFacade handleShutdown() #3 {main} [] []

Apache error log, has the missing part of the grav.log:

>PHP Fatal error:  'break' not in the 'loop' or 'switch' context in /var/www/grav/user/plugins/snappygrav/classes/snappymanager.php on line 273

Apparently since 7.0 break statment are only allowed inside for, foreach, while, do-while or switch structure.

**Comment by iusvar** [comment]
Hi,

I corrected the error by completely removing the control that is virtually unnecessary. (Anyway I would have to replace break with exit :smile: )

I'm telling you that the error will be repeated because your wkhtmltopdf library is not correct ...

**Comment by anj4u** [comment]
same here, do you solve this?

**Comment by iusvar** [comment]
Already solved with [version 1.5.1](https://github.com/iusvar/grav-plugin-snappygrav/releases) 
I do not know why it is not updated in [https://getgrav.org/downloads/plugins](https://getgrav.org/downloads/plugins)

**Comment by iusvar** [comment]
Updates did not appear regularly because I used dates in the wrong format in CHANGELOG.md
On the forum rhukster [has solved my doubt](https://discourse.getgrav.org/t/plugin-upgrade-issues/4161).
Fixed with version 1.5.2 that will appear shortly ...

Thanks for the warning
