### ISSUE TITLE
SnappyGrav Error Print all site

### ISSUE THREAD

**Issue by matthieud69** [iusvar/grav-plugin-snappygrav#21]
Hi, 
After an update of snappygrav (v1.5.2), the export of all pages no longer works and tells me an error message (see below)
`` `
Error 1
An error occurred. Undefined variable: where
`` `
 Theme version Learn2: 1.7.0
GRAV Version: Grav v1.3.2 - Admin v1.5.2
Syntax of the file sidebar.html.twig: {{snappygrav ()}}
On the other hand the {{snappygrav (page.route)}} works very well.

**Comment by iusvar** [comment]
Hi,
can you tell me the subfolders' names in the `user/themes` folder?

**Comment by matthieud69** [comment]
Hi, 
Thank you for your reply.
The theme is "LEARN2" and its subfolders: blueprints, CHANGELOG.md, css-compiled, fonts, images, languages.yaml, learn2.yaml README.md, scss, templates, blueprints.yaml, css, .editorconfig .gitignore , js learn2.php, LICENSE, screenshot.jpg, scss.sh, thumbnail.jpg

**Comment by iusvar** [comment]
The new release is online on github, soon it will be available on GPM.
Regards
