### ISSUE TITLE
Error 1 on complete site export

### ISSUE THREAD

**Issue by mckaulay** [iusvar/grav-plugin-snappygrav#24]
I've installed the plugin's most recent version (1.5.5) on http://www.launchschoolhr.org/ and added the full site export button to the learn2 sidebar. On export it produces this error:

> ## Error 1 
> `An error occurred. The exit status code '127' says something went wrong: stderr: "/home/makiadmin/public_html/host/launchschool/hr-manual/user/plugins/snappygrav/vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory " stdout: "" command: /home/makiadmin/public_html/host/launchschool/hr-manual/user/plugins/snappygrav/vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386 --lowquality --margin-bottom '10' --margin-left '10' --margin-right '10' --margin-top '10' --page-size 'letter' --zoom '1' '/tmp/knp_snappy59bdf6f768a808.56701056.html' '/tmp/knp_snappy59bdf6f768b036.70725285.html' '/tmp/knp_snappy59bdf6f768b3e2.03949649.html' '/tmp/knp_snappy59bdf6f768b6f4.97454411.html' '/tmp/knp_snappy59bdf6f768b9f1.72760616.html' '/tmp/knp_snappy59bdf6f768bcc1.18990840.html' '/tmp/knp_snappy59bdf6f768bfb8.47072110.html' '/tmp/knp_snappy59bdf6f768c287.22381920.html' '/tmp/knp_snappy59bdf6f768c568.38021724.html' '/tmp/knp_snappy59bdf6f768c832.01600594.html' '/tmp/knp_snappy59bdf6f768cb04.57468339.html' '/tmp/knp_snappy59bdf6f768cde9.11122782.html' '/tmp/knp_snappy59bdf6f768d0b4.86055825.html' '/tmp/knp_snappy59bdf6f768d376.68214710.html' '/tmp/knp_snappy59bdf6f768d644.64946557.html' '/tmp/knp_snappy59bdf6f768d901.74254855.html' '/tmp/knp_snappy59bdf6f768dbc3.89926786.html' '/tmp/knp_snappy59bdf6f768de71.30684862.html' '/tmp/knp_snappy59bdf6f768e134.81352581.html' '/tmp/knp_snappy59bdf6f768e4b6.10281751.html' '/tmp/knp_snappy59bdf6f768e843.75437065.html' '/tmp/knp_snappy59bdf6f768eb18.71227611.html' '/tmp/knp_snappy59bdf6f768eea5.34695759.html' '/tmp/knp_snappy59bdf6f768f1c3.32005357.html' '/tmp/knp_snappy59bdf6f768f499.05286553.html' '/tmp/knp_snappy59bdf6f768f761.11608725.html' '/tmp/knp_snappy59bdf6f768fa37.50580394.html' '/tmp/knp_snappy59bdf6f768fce5.56920474.html' '/tmp/knp_snappy59bdf6f768ffc2.50271102.html' '/tmp/knp_snappy59bdf6f7690288.71894712.html' '/tmp/knp_snappy59bdf6f7690539.98593038.html' '/tmp/knp_snappy59bdf6f7690804.12784606.html' '/tmp/knp_snappy59bdf6f7690ad9.42337369.html' '/tmp/knp_snappy59bdf6f7690dc1.67621700.html' '/tmp/knp_snappy59bdf6f76910b5.93171251.html' '/tmp/knp_snappy59bdf6f7691393.78104100.html' '/tmp/knp_snappy59bdf6f7691651.07273267.html' '/tmp/knp_snappy59bdf6f7691919.91936517.html' '/tmp/knp_snappy59bdf6f7691cc6.40143429.html' '/tmp/knp_snappy59bdf6f7691fb9.64597977.html' '/tmp/knp_snappy59bdf6f7692277.66553746.html' '/tmp/knp_snappy59bdf6f7692528.46254551.html' '/tmp/knp_snappy59bdf6f76928e4.91292239.html' '/tmp/knp_snappy59bdf6f7692c87.67321737.html' '/tmp/knp_snappy59bdf6f7692fc4.15394628.html' '/tmp/knp_snappy59bdf6f7693294.87984640.html' '/tmp/knp_snappy59bdf6f7693559.87248371.html' '/tmp/knp_snappy59bdf6f7693817.31289588.html' '/tmp/knp_snappy59bdf6f7693ad2.20059616.html' '/tmp/knp_snappy59bdf6f7693e31.68448063.html' '/tmp/knp_snappy59bdf6f7694108.98575354.html' '/tmp/knp_snappy59bdf6f76943c2.94305235.html' '/tmp/knp_snappy59bdf6f7694672.28726853.html' '/tmp/knp_snappy59bdf6f7694936.75067308.html' '/tmp/knp_snappy59bdf6f7694bd2.06435666.html' '/tmp/knp_snappy59bdf6f7694e77.57837584.html' '/tmp/knp_snappy59bdf6f7695135.80819945.html' '/tmp/knp_snappy59bdf6f7695405.84474281.html' '/tmp/knp_snappy59bdf6f76956e2.63078480.html' '/tmp/knp_snappy59bdf6f76959a1.10055851.html' '/tmp/knp_snappy59bdf6f7695c46.45248288.html' '/tmp/knp_snappy59bdf6f7695ef3.74824289.html' '/tmp/knp_snappy59bdf6f76961d9.88176781.html' '/tmp/knp_snappy59bdf6f7696517.47677623.html' '/tmp/knp_snappy59bdf6f76967e6.83094746.html' '/tmp/knp_snappy59bdf6f7696be8.39099912.html' '/tmp/knp_snappy59bdf6f7696f89.78943844.html' '/tmp/knp_snappy59bdf6f7697250.58678239.html' '/tmp/knp_snappy59bdf6f7697531.78859816.html' '/tmp/knp_snappy59bdf6f7697803.47290476.html' '/tmp/knp_snappy59bdf6f7697ac6.46694617.html' '/tmp/knp_snappy59bdf6f7697d92.24537232.html' '/tmp/knp_snappy59bdf6f7698052.33275562.html' '/tmp/knp_snappy59bdf6f7698302.53792449.html' '/tmp/knp_snappy59bdf6f76985d2.33351011.html' '/tmp/knp_snappy59bdf6f76988a6.92527130.html' '/tmp/knp_snappy59bdf6f7698b77.55170859.html' '/tmp/knp_snappy59bdf6f7698e33.04597374.html' '/tmp/knp_snappy59bdf6f76990f2.16165443.html' '/tmp/knp_snappy59bdf6f76993b0.96545581.html' '/tmp/knp_snappy59bdf6f7699691.73624063.html' '/tmp/knp_snappy59bdf6f7699963.42611852.html' '/tmp/knp_snappy59bdf6f7699c20.67960559.html' '/tmp/knp_snappy59bdf6f7699ef3.35874366.html' '/tmp/knp_snappy59bdf6f769a1d6.02608503.html' '/tmp/knp_snappy59bdf6f769a491.10100731.html' '/tmp/knp_snappy59bdf6f769a7f4.28125454.html' '/tmp/knp_snappy59bdf6f769aaf7.87312178.html' '/tmp/knp_snappy59bdf6f769ae08.90075838.html' '/tmp/knp_snappy59bdf6f769b1d7.44973233.html' '/tmp/knp_snappy59bdf6f769b4c8.27197758.html' '/tmp/knp_snappy59bdf6f769b7a5.58407578.html' '/tmp/knp_snappy59bdf6f769ba88.20241992.html' '/tmp/knp_snappy59bdf6f769bdd7.54212601.html' '/tmp/knp_snappy59bdf6f769c0a2.58784187.html' '/tmp/knp_snappy59bdf6f769c3a2.24668608.html' '/tmp/knp_snappy59bdf6f769c680.89131273.html' '/tmp/knp_snappy59bdf6f769c921.22930751.html' '/tmp/knp_snappy59bdf6f769cc67.96428241.pdf'.`

At first I guessed that there might be an issue with the `wk_path` configuration, but it seems more like it has to do with `libXrender.so.1`. I'm running on GoDaddy shared Linux hosting, so maybe I need to find a way to install libXrender.so.1. Thanks in advance for any help you can give me.

**Comment by iusvar** [comment]
Download the **static version** (containing missing libraries), available on the wkhtmltopdf website choosing the right one for the GoDaddy operating system, so probably amd64
