### ISSUE TITLE
60 sec timeout

### ISSUE THREAD

**Issue by roelfrenkema** [iusvar/grav-plugin-snappygrav#25]
Hi all,

Snappy working fine untill I set Absolute urls to get images in the PDF's Whe I try to create a pdf after that it will stop after to seconds complaining about a 60sec timeout. This seems to happen to snappy and people talk several solutions on the snappy pages but as snappygrav is different in setup I see no way too implement them. F.I. a timeout variable in a config/snappy.php file that people talk about. Anyone any idea how to solve this?

**Comment by iusvar** [comment]
Hi,
I would need more information.
Grav version? In what environment do you use snappygrav: antimatter, learn, knowledge? Are you printing a single document or the entire site?

One more thing. When you type `"people talk several solutions on the snappy pages but as snappygrav is different in setup I see no way too implement them"`, does it mean that you have any suggestions?

**Comment by iusvar** [comment]
Released new version.
