### ISSUE TITLE
Notice boxes are not rendered in PDF

### ISSUE THREAD

**Issue by shivahnshankar** [iusvar/grav-plugin-snappygrav#26]
I am using markdown-notices plugin for notice blocks. The text in these boxes are included in the PDF but not the box itself. 
Is there any option to faithfully render the entire page as it appears in the browser?

**Comment by iusvar** [comment]
Good news. Changes already made.

Before creating a new release, and making it available on Grav, would you like to try the procedure by downloading directly from https://github.com/iusvar/grav-plugin-snappygrav/archive/master.zip?

**Comment by iusvar** [comment]
Great, good teaching!
