### ISSUE TITLE
Getting the following error: ... The exit status code '127' says something went wrong

### ISSUE THREAD

**Issue by marcos1990** [iusvar/grav-plugin-snappygrav#28]
I really can't figure out what is wrong here.

When I click on the export button I get:

![screen shot 2018-02-01 at 3 56 29 pm](https://user-images.githubusercontent.com/3341610/35702998-ad011c68-0768-11e8-9460-6d6b11eb9e1a.png)

I am using the {{ snappygrav() }} in my template partial and I have installed knp-snappy and wkhtmltopdf-i386

My setup:
- Learn2 theme
- Grav 1.3.9
- PHP 5.6.33
- Alpine 6.3.0
- Docker 17.12.0-ce

Many thanks

**Comment by iusvar** [comment]
The wkhtmltopdf-i386 library was not found in the `/var/www/grav-admin/user/plugins/snappygrav/vendor/h4cc/wkhtmltopdf-i386/bin/` directory...

**Comment by marcos1990** [comment]
Dear iusvar,

Thanks for your answer. 

I've finally installed it at the OS level using the following step:

`
$ wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz 
$ tar -xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz 
$ cd wkhtmltox/bin/
$ mv wkhtmltopdf /usr/bin/wkhtmltopdf
$ mv wkhtmltoimage /usr/bin/wkhtmltoimage 
$ chmod a+x /usr/bin/wkhtmltopdf
$ chmod a+x /usr/bin/wkhtmltoimage
`

In addition, i've changed the snappygrav.yaml values:
`
wk_absolute_pos: true          # True meaning under the plugin, fake under the operating system (default = false)
wk_path: /usr/bin/wkhtmltopdf     
`

It is exporting fine now. I couldn't install using composer for some reason.

**Comment by iusvar** [comment]
Thanks for the summary that might be useful for someone else. Probably some parts will insert them in the readme.
Well done :smile:
