### ISSUE TITLE
media files doesn't appear in saved pdf

### ISSUE THREAD

**Issue by motherfacker** [iusvar/grav-plugin-snappygrav#29]
When i save page with images it's doesnt appear in pdf file.

**Comment by iusvar** [comment]
To include images requires a true value for the Absolute URLs in the system.yaml file. Try checking this

**Comment by motherfacker** [comment]
> To include images requires a true value for the Absolute URLs in the system.yaml file. Try checking this
Checked. Absolute URLs has a true value but doesn't work anyway.

**Comment by iusvar** [comment]
Can you provide the web address of your site?

**Comment by motherfacker** [comment]
> Can you provide the web address of your site?
my website - oftbook.cf
