### ISSUE TITLE
Pages are not ordered

### ISSUE THREAD

**Issue by fheslouin** [iusvar/grav-plugin-snappygrav#30]
Created PDF contain pages in disorder. 

I'm using learn2 themes + snappyGrav plugin. My pages use folder numeric prefix.

I noticed that the last added pages are shown first in the PDF, I would like to orderer the PDF differently and use the folder numeric prefix. 

Can someone point me to the procedure ? 

Thanks

**Comment by iusvar** [comment]
The order in which the pdf file is created depends on what is saved in the `user/config/system.yaml` file under / `System` / `Content` / `Default ordering`.
Take a look

**Comment by fheslouin** [comment]
Thanks for your help.

Here is what I have in my `system.yaml` file : 
```
pages:
  theme: learn2-git-sync
  order:
    by: default
    dir: asc
  list:
    count: 20
```

Pages are correctly shown on the website, I mean based on folder name with prefix
```
01.home
02.contact
....
```
However, the created PDF does not reflect the folder organization, I don't understand why...

**Comment by iusvar** [comment]
I made a change that should solve the issue.
It will soon be available in the GPM.

**Comment by fheslouin** [comment]
Great thanks a lot. 

I'll report the result here

**Comment by iusvar** [comment]
Should it work, please close the issue, thank you

**Comment by fheslouin** [comment]
Thanks very much ! It is working perfectly
