### ISSUE TITLE
Error proc_open

### ISSUE THREAD

**Issue by motherfacker** [iusvar/grav-plugin-snappygrav#31]
Hi
i'm setup snappygrav and wkhtmltopdf and have error:
"The Process class relies on proc_open, which is not available on your PHP installation."
My hoster says that they proc_open disable for security reasons and other hosters says too
What should i do that it works?
Thanks

**Comment by iusvar** [comment]
Hi, what's your hoster?

**Comment by motherfacker** [comment]
> Hi, what's your hoster?
This one [https://webhost1.ru/](webhost1.ru)

**Comment by iusvar** [comment]
I have just published a new version that uses the replacement libraries of wkhtmltopdf: mPDF and TCPDF.

So this problem could be unresolved but ... let's say avoided :smile:
