### ISSUE TITLE
Search text not aligned with learn2 theme if snappygrav plugin is enabled

### ISSUE THREAD

**Issue by christianhals** [iusvar/grav-plugin-snappygrav#32]
It´s the same issue mentioned in the repository for Learn2: https://github.com/getgrav/grav-theme-learn2/issues/72

Issue is resolved by disabling the snappygrav-plugin, so I would think it must be an issue with Snappygrav and not the Learn2 theme. I´ve added a temporary workaround by adding some placeholders, but would be great to see a fix for this.

I´m running the latest current versions: SnappyGrav v1.6.1, Learn2 1.7.0 and Grav v1.5.1

**Comment by iusvar** [comment]
The issue was caused by a bit of useless css.
I will make a new version as soon as I have solved some other issue.
Thanks for the tip.

**Comment by christianhals** [comment]
Thanks a lot for your swift reply. Look forward to the new version:-)

**Comment by iusvar** [comment]
Released new version.

**Comment by christianhals** [comment]
Thanks a lot for the update. Is this a new 1.61 --> 1.62 GPM-version? I could not find any updates by running GPM index or update.

I can confirm that replacing the css manually with the new file has resolved the issue for me:-)

**Comment by iusvar** [comment]
GPM sees the new releases after a few hours.
Now Snappygrav 1.6.2 is available with GPM.

**Comment by christianhals** [comment]
I see the update now and it is working fine. Thanks again.
