### ISSUE TITLE
1.62 - Markdown Info

### ISSUE THREAD

**Issue by christianhals** [iusvar/grav-plugin-snappygrav#34]
After I updated to 1.62 via GPM I´m no longer seeing the markdown notice highlighting in my PDF´s. The text is still there, but without the formatting. Are there any new changes introduced in 1.62 that might break this feature?

**Comment by iusvar** [comment]
Not that I know, I will check

**Comment by christianhals** [comment]
I updated to the latest 1.70 via GPM and issue seems to be resolved. I really appreciate your hard work and swift replies.
