### ISSUE TITLE
Invalid Security Token Message

### ISSUE THREAD

**Issue by andrekutianski** [iusvar/grav-plugin-snappygrav#46]
When I try to download a specific page on my Grav I receive the message:

> Invalid Security Token - Refresh page with F5 and try again

![](https://image.prntscr.com/image/0F21D9k3RgWPEjKYNvdkUg.png)

All other pages work fine, just only one page that this occurs .

Using Grav v1.5.7 - Admin v1.8.16

**Comment by iusvar** [comment]
It is not an issue, it's a desired effect when someone spends some time doing nothing

**Comment by andrekutianski** [comment]
Sorry, I don't understand. I access the page, click in export and this is the desired effect? Show invalid security token?

**Comment by iusvar** [comment]
Do you happen as soon as you go to that page?

**Comment by andrekutianski** [comment]
Yes, @iusvar after access the page I try to export, but soon I click on the button this message appears. I using mPDF.
If you want to give a try the link is https://serasa.eunarede.com/pefin/administracao (this page and all pages inside this show the same problem).

**Comment by iusvar** [comment]
As you wrote it does not work on some pages ... so it should depend on the content of the particular page, weird

**Comment by andrekutianski** [comment]
I double checked all content but there are no big differences, to be honest only the folder hierarchy and content changes. The log is clear and I have deactivated all non-essential plugins.

now I have only to try changing the structure directories to see what happens

**Comment by andrekutianski** [comment]
I changed the pages to another folder and work again, very weird.

**Comment by iusvar** [comment]
Who knows what it was! Any hidden character in the name? Just weird.

**Comment by andrekutianski** [comment]
> Who knows what it was! Any hidden character in the name? Just weird.
> Like in a Woody Allen film, the important thing that works!

No hidden characters, just change the folder and works!
