### ISSUE TITLE
Pdf button

### ISSUE THREAD

**Issue by Quentinvarquet** [iusvar/grav-plugin-snappygrav#9]
Hello,

I am using wamp with apache on my windows laptop.

I can't export a PDF with the button, I have a 404 error.

I changed the Parameter separator (: to ;) but I still have the problem..

Any idea ?

**Comment by iusvar** [comment]
Check content of **wk_paths** field in **snappygrav.xml** file.
The default content is fine for a Linux / Mac system. I mean slashes: in windows must be backslashes...
Paramenter separator in ONLY colon ( : )

**Comment by Quentinvarquet** [comment]
Fixed,
Thank you
